name: gps_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.0.1
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_background_service_ios: ^2.4.0
  permission_handler: ^10.2.0
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  gsheets: ^0.5.0
  flutter_local_notifications: ^16.3.2
  background_location: ^0.11.8
  provider: ^6.1.1
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true